// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rszlyaouqcwfyexggbmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzemx5YW91cWN3ZnlleGdnYm10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDU1NjgsImV4cCI6MjA1NzM4MTU2OH0.7_DqISn8FFYhluHKrfHfikbqprRQRBXBYnu07TkSW7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);